[profile.default]
    src = 'src'
    out = 'out'
    libs = ['lib']
    remappings = [
        "openzeppelin/=lib/openzeppelin-contracts/contracts",
        "solady/=lib/solady/src",
        "forge-std/=lib/forge-std/src",
    ]
    solc_version = "0.8.20"
    verbosity = 3

[profile.ci]
    fuzz = { runs = 5000 }
    invariant = { runs = 1000 }

[profile.lite]
    fuzz = { runs = 50 }
    invariant = { runs = 10 }
    # Speed up compilation and tests during development.
    optimizer = false

[fmt]
    bracket_spacing = false
    ignore = ["src/lib/*.sol"]
    int_types = "long"
    line_length = 100
    multiline_func_header = "attributes_first"
    number_underscore = "thousands"
    quote_style = "double"
    single_line_statement_blocks = "single"
    tab_width = 2
    wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config